baseurl: "/"
languageCode: "en-us"
title: "Linear Statistical Modelling"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:slug/"
  post: "/post/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: Notes
      url: "note/"
      weight: 2
    - name: Units
      url: "categories/"
      weight: 3
    - name: Tags
      url: "tags/"
      weight: 4

params:
  description: "Tuition notes to support M346 - statistical linear modelling"
  footer: "&copy; [richard johnson](https://deeprich.net) 2021 | [Github](https://github.com/deeprich)"

markup:
  goldmark:
    renderer:
      unsafe: true
