# Site settings
baseURL = "https://lm.deeprich.net"
languageCode = "en-us"
title = "Linear Statistical Modelling"
theme = "hugo-simpledoc-theme"

[blackfriday]
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  smartlists = true
  extensions = ["hardLineBreak"]

# Top menu
[[menu.top]]
    name = "index"
    weight = 20
    url = "https://lm.deeprich.net"
[[menu.top]]
    name = "home"
    weight = 10
    url = "https://www.deeprich.net"

# Site parameters
[params]

    # Meta
    description = "Resources to help undergraduates with linear statistical modelling"
    author = "Richard Johnson"
    keywords = "linear model, lm, regression, statistics, inference"
    
    # Header
    # If not set, site title and meta description will be shown.
    # You may use markdown here
    headerTitle = "Linear Statistical Modelling"
    headerDescription = "Collection of guides and resources for statistical inference"
    
    # Back-to-top button name
    bttButton = ""